# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, pkgs
, lib
, fetchurl
, installShellFiles
, makeWrapper
, stdenv
, gh
}:
let
  shaMap = {
    x86_64-linux = "0sc5n0nw48sy0nndz8rd7cih433jfkhikiby013f8scpf2vsqgwq";
    aarch64-linux = "1hvhgd5dmbi4dvzr9lan8y49srbjbl2x7hwjgbk0kix592zqg54d";
    x86_64-darwin = "07qg9wghnrv26azwngkngg8s77y805wi6q3vma5is0w5bd3yn72p";
    aarch64-darwin = "07qg9wghnrv26azwngkngg8s77y805wi6q3vma5is0w5bd3yn72p";
  };

  urlMap = {
    x86_64-linux = "https://github.com/flexwie/ghs/releases/download/v0.2/ghs_0.2_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/flexwie/ghs/releases/download/v0.2/ghs_0.2_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/flexwie/ghs/releases/download/v0.2/ghs_0.2_darwin_all.tar.gz";
    aarch64-darwin = "https://github.com/flexwie/ghs/releases/download/v0.2/ghs_0.2_darwin_all.tar.gz";
  };
in
pkgs.stdenv.mkDerivation {
  pname = "ghs";
  version = "0.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./ghs $out/bin/ghs
    wrapProgram $out/bin/ghs --prefix PATH : ${lib.makeBinPath ([ gh ])}
  '';

  system = system;

  meta = {
    description = "a npx-like script execution for gists";
    homepage = "https://github.com/flexwie/ghs";
    license = lib.licenses.MIT;

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
