# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, pkgs
, lib
, fetchurl
, installShellFiles
, makeWrapper
, stdenv
, gh
}:
let
  shaMap = {
    x86_64-linux = "1i43yc99r9yiw7h5nfhf3zd5n8j808xpyl0y87737kgvflkwh6pp";
    aarch64-linux = "10v07kc84nxsmy2a1mscqkws77jr344i4r8r0w2lp6pjyfj99ll7";
    x86_64-darwin = "0jfzfklw8dgxkwvxp0asi0hpw15w51cbzin21qa37h2jsb6xlggv";
    aarch64-darwin = "0jfzfklw8dgxkwvxp0asi0hpw15w51cbzin21qa37h2jsb6xlggv";
  };

  urlMap = {
    x86_64-linux = "https://github.com/flexwie/ghs/releases/download/v0.1/ghs_0.1_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/flexwie/ghs/releases/download/v0.1/ghs_0.1_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/flexwie/ghs/releases/download/v0.1/ghs_0.1_darwin_all.tar.gz";
    aarch64-darwin = "https://github.com/flexwie/ghs/releases/download/v0.1/ghs_0.1_darwin_all.tar.gz";
  };
in
pkgs.stdenv.mkDerivation {
  pname = "ghs";
  version = "0.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./ghs $out/bin/ghs
    wrapProgram $out/bin/ghs --prefix PATH : ${lib.makeBinPath ([ gh ])}
  '';

  system = system;

  meta = {
    description = "a npx-like script execution for gists";
    homepage = "https://github.com/flexwie/ghs";
    license = lib.licenses.MIT;

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
