# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, pkgs
, lib
, fetchurl
, installShellFiles
, makeWrapper
, stdenv
, gh
}:
let
  shaMap = {
    x86_64-linux = "07dq44309q25lgzrq9fr6n5gsj610cic8qgrcpipl0n6z5kvw1km";
    aarch64-linux = "13v5j74470i9f31zbbrzcci8xi0c3p3ifk6mabqpwz90r3a4q543";
    x86_64-darwin = "01l435bss7c8i75ps64gbns56kx9waiwp9vgf9mqjdwrm5fnm24h";
    aarch64-darwin = "01l435bss7c8i75ps64gbns56kx9waiwp9vgf9mqjdwrm5fnm24h";
  };

  urlMap = {
    x86_64-linux = "https://github.com/flexwie/ghs/releases/download/v0.1/ghs_0.1_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/flexwie/ghs/releases/download/v0.1/ghs_0.1_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/flexwie/ghs/releases/download/v0.1/ghs_0.1_darwin_all.tar.gz";
    aarch64-darwin = "https://github.com/flexwie/ghs/releases/download/v0.1/ghs_0.1_darwin_all.tar.gz";
  };
in
pkgs.stdenv.mkDerivation {
  pname = "ghs";
  version = "0.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./ghs $out/bin/ghs
    wrapProgram $out/bin/ghs --prefix PATH : ${lib.makeBinPath ([ gh ])}
  '';

  system = system;

  meta = {
    description = "a npx-like script execution for gists";
    homepage = "https://github.com/flexwie/ghs";
    license = lib.licenses.MIT;

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
